#pragma once

#define BOUNDS_WIDTH 1024
#define BOUNDS_HEIGHT 1024

#define SCREEN_TOP_PADDING (96)
#define SCREEN_PADDING (32)
#define SCREEN_WIDTH (BOUNDS_WIDTH + 2 * SCREEN_PADDING)
#define SCREEN_HEIGHT (BOUNDS_HEIGHT + SCREEN_PADDING + SCREEN_TOP_PADDING)

#define MAX_BALLS (1024 * 1024)
#define QUADTREE_MAX_DEPTH (5)
#define MAX_NEARBY_ITEMS (1024 * 16)

#define STEP_TIME (1.0)
